name: Destroy AWS Infrastructure

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=tfplan-destroy

      - name: Terraform Destroy
        run: terraform apply -auto-approve tfplan-destroy
