name: Destroy AWS Infrastructure (Terragrunt)

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1

jobs:
  terragrunt-destroy:
    name: Terragrunt Destroy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.2.0
        with:
          terragrunt_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terragrunt Destroy
        run: cd terraform/terragrunt && terragrunt run-all destroy --terragrunt-non-interactive -auto-approve
